#!/bin/bash

mkdir -p generated/tiger/

echo "
CREATE SCHEMA IF NOT EXISTS ACS_TIGER_SHAPE;
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
" > generated/tiger/tiger_schema.sql

echo "
ALTER TABLE ACS_TIGER_SHAPE.CENSUS_TRACT_2010 ADD COLUMN year VARCHAR(4) NOT NULL DEFAULT 2010;
ALTER TABLE ACS_TIGER_SHAPE.CENSUS_TRACT_2010 DROP CONSTRAINT census_tract_2010_pkey;
ALTER TABLE ACS_TIGER_SHAPE.CENSUS_TRACT_2000 ADD COLUMN year VARCHAR(4) NOT NULL DEFAULT 2000;
ALTER TABLE ACS_TIGER_SHAPE.CENSUS_TRACT_2000 DROP CONSTRAINT census_tract_2000_pkey;
INSERT INTO ACS_TIGER_SHAPE.CENSUS_TRACT_2010 SELECT * FROM ACS_TIGER_SHAPE.CENSUS_TRACT_2000;
ALTER TABLE ACS_TIGER_SHAPE.CENSUS_TRACT_2010 RENAME TO CENSUS_TRACT;
DROP TABLE ACS_TIGER_SHAPE.CENSUS_TRACT_2000;
ALTER TABLE ACS_TIGER_SHAPE.CENSUS_TRACT ALTER COLUMN year DROP DEFAULT;
" > generated/tiger/census_tract.sql